# ============================================================
# HP iLO - DL20 Gen10
# Raw data sensors - referenced by template sensors
# in entities/template/hp_ilo.yaml
# ============================================================
- platform: hp_ilo
  host: !secret ilo_dl20_host
  username: !secret ilo_username
  password: !secret ilo_password
  monitored_variables:
    - name: PVE Node 1 Processors
      sensor_type: server_health
      value_template: "{{ ilo_data.processors['Proc 1'].name }}"

    - name: PVE Node 1 Memory
      sensor_type: server_health
      value_template: "{{ ilo_data.memory.memory_details_summary.cpu_1.total_memory_size }} @ {{ ilo_data.memory.memory_details_summary.cpu_1.operating_frequency }}"

    # -------------------------
    # Power Status / Uptime
    # -------------------------
    - name: PVE Node 1 Power Status
      sensor_type: server_power_status

    - name: PVE Node 1 Power On Time
      sensor_type: server_power_on_time
      unit_of_measurement: "min"

    # -------------------------
    # Power Readings
    # -------------------------
    - name: PVE Node 1 Present Power
      sensor_type: server_power_readings
      unit_of_measurement: "W"
      value_template: "{{ ilo_data.present_power_reading[0] }}"

    - name: PVE Node 1 Average Power
      sensor_type: server_power_readings
      unit_of_measurement: "W"
      value_template: "{{ ilo_data.average_power_reading[0] }}"

    - name: PVE Node 1 Minimum Power
      sensor_type: server_power_readings
      unit_of_measurement: "W"
      value_template: "{{ ilo_data.minimum_power_reading[0] }}"

    - name: PVE Node 1 Maximum Power
      sensor_type: server_power_readings
      unit_of_measurement: "W"
      value_template: "{{ ilo_data.maximum_power_reading[0] }}"
      
    # -------------------------
    # Fan Sensors
    # Fan names may vary: Fan 1, Fan 2, Fan 3, etc.
    # -------------------------
    - name: PVE Node 1 Fan 1 Speed
      sensor_type: server_health
      unit_of_measurement: "%"
      value_template: "{{ ilo_data.fans['Fan 1'].speed[0] | default('unknown') }}"

    - name: PVE Node 1 Fan 2 Speed
      sensor_type: server_health
      unit_of_measurement: "%"
      value_template: "{{ ilo_data.fans['Fan 2'].speed[0] | default('unknown') }}"

    - name: PVE Node 1 Fan 3 Speed
      sensor_type: server_health
      unit_of_measurement: "%"
      value_template: "{{ ilo_data.fans['Fan 3'].speed[0] | default('unknown') }}"


    # -------------------------
    # Temp Sensors
    # Fan names may vary: Fan 1, Fan 2, Fan 3, etc.
    # -------------------------
    - name: PVE Node 1 Inlet Temp
      sensor_type: server_health
      unit_of_measurement: "°C"
      value_template: "{{ ilo_data.temperature['01-Inlet Ambient'].currentreading[0] | default('unknown') }}"

    - name: PVE Node 1 Exhaust Temp
      sensor_type: server_health
      unit_of_measurement: "°C"
      value_template: "{{ ilo_data.temperature['25-System Board'].currentreading[0] | default('unknown') }}"

    - name: PVE Node 1 CPU Temp
      sensor_type: server_health
      unit_of_measurement: "°C"
      value_template: "{{ ilo_data.temperature['02-CPU 1'].currentreading[0] | default('unknown') }}"

    - name: PVE Node 1 System Board Temp 1
      sensor_type: server_health
      unit_of_measurement: "°C"
      value_template: "{{ ilo_data.temperature['10-System Board'].currentreading[0] | default('unknown') }}"

    - name: PVE Node 1 HDD Temp
      sensor_type: server_health
      unit_of_measurement: "°C"
      value_template: "{{ ilo_data.temperature['04-HD Max'].currentreading[0] | default('unknown') }}"

    - name: PVE Node 1 Power Supply 1 Temp
      sensor_type: server_health
      unit_of_measurement: "°C"
      value_template: "{{ ilo_data.temperature['21-P/S 1'].currentreading[0] | default('unknown') }}"

    - name: PVE Node 1 Power Supply 2 Temp
      sensor_type: server_health
      unit_of_measurement: "°C"
      value_template: "{{ ilo_data.temperature['22-P/S 2'].currentreading[0] | default('unknown') }}"

    # All Temp Sensors
    # "01-Inlet Ambient", "02-CPU 1", "03-P1 DIMM 1-4", "04-HD Max", "05-Chipset", "06-VR P1",
    # "07-Stor Batt 1", "08-BMC", "09-BMC Zone", "10-System Board", "11-PCI 1", 
    #  "12-PCI 2", "13-PCI 1 Zone", "14-PCI 2 Zone", "15-HD Controller", 
    #  "16-HD Cntlr Zone", "17-LOM Card", "18-LOM", "19-P/S 1 Inlet", "20-P/S 2 Inlet", "21-P/S 1", "22-P/S 2", "23-P/S Zone", "24-M2", "25-System Board", "26-AHCI HD Max", "27-M2 Zone"

    # -------------------------
    # Overall Health
    # -------------------------
    - name: PVE Node 1 Fans Health
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance.fans.status | default('unknown') }}"

    - name: PVE Node 1 Temperature Health
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance.temperature.status | default('unknown') }}"

    - name: PVE Node 1 Power Supplies Health
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance.power_supplies.status | default('unknown') }}"

    - name: PVE Node 1 Processor Health
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance.processor.status | default('unknown') }}"

    - name: PVE Node 1 Memory Health
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance.memory.status | default('unknown') }}"

    - name: PVE Node 1 Network Health
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance.network.status | default('unknown') }}"

    - name: PVE Node 1 Storage Health
      sensor_type: server_health
      value_template: "{{ ilo_data.health_at_a_glance.storage.status | default('unknown') }}"     