alias: ' 🏠 House :💡 Dining 9W Light '

id: f46b9967-14e8-4a77-af4e-5124cb1b6e67

description: ''

mode: restart

trigger:
  - platform: time
    at: '17:00:00'

  - platform: time
    at: '05:30:00'

  - platform: time
    at: '20:30:00'

  - platform: state
    entity_id:
      - light.dining_9w_philips_light
    from: unavailable
    to: 'on'

action:
  - choose:

      - conditions:
          - condition: or
            conditions:
              - condition: time
                before: '20:00:00'
                after: '17:00:00'

              - condition: time
                before: '06:00:00'
                after: '05:30:00'

        sequence:
          - service: script.light_handler
            data:
              light:
                entity_id: light.dining_9w_philips_light
              power_mode: 'On'

      - conditions:
          - condition: time
            before: '05:29:55'
            after: '20:29:55'

        sequence:
          - service: script.light_handler
            data:
              light:
                entity_id: light.dining_9w_philips_light
              power_mode: Indoor Night Lamp
              brightness: 10

    default:
      - service: script.light_handler
        data:
          light:
            entity_id: light.dining_9w_philips_light
          power_mode: 'Off'