alias: "🏠 House :💡 Hall 9W Light"
id: 68ab71e9-6ed6-43b4-a543-28368ef93e40
mode: restart

trigger:
  - platform: state
    id: power-restored
    entity_id:
      - light.hall_9w
    from: unavailable
    to: 'on'

  - platform: time
    at: '17:00:00'
    id: evening-mode-start

  - platform: time
    at: '18:00:00'
    id: evening-mode-stop

  - platform: time
    at: '20:00:00'
    id: night-mode-start

  - platform: time
    at: '20:30:00'
    id: night-lamp-on

  - platform: time
    at: '05:30:00'
    id: morning-mode-start

  - platform: time
    at: '05:45:00'
    id: power-off


action:
  # Power On 100%
  - if:
      - condition: or
        conditions:
          - condition: trigger
            id: evening-mode-start
          - condition: trigger
            id: night-mode-start
          - condition: trigger
            id: morning-mode-start
          - condition: and
            conditions:
              - condition: trigger
                id: power-restored
              - condition: or
                conditions:
                  # 04:59 - 05:59 PM
                  - condition: time
                    after: '16:59:55'
                    before: '17:59:55'

                  # 07:29 - 08:29 PM
                  - condition: time
                    after: '19:29:55'
                    before: '20:29:55'

                  # 05:29 - 05:44 AM
                  - condition: time
                    after: '05:29:55'
                    before: '05:44:55'
    then:
      - service: script.light_handler
        data:
          light:
            entity_id: light.hall_9w
          power_mode: 'On'
          brightness: 100

  # Night Lamp
  - if:
      - condition: or
        conditions:
          - condition: trigger
            id: night-lamp-on
          - condition: and
            conditions:
              - condition: trigger
                id: power-restored
              - condition: time
                before: '05:29:54'
                after: '20:29:56'
    then:
      - service: script.light_handler
        data:
          light:
            entity_id: light.hall_9w
          power_mode: Indoor Night Lamp
          brightness: 25



  # Power Off
  - if:
      - condition: or
        conditions:
          - condition: trigger
            id: evening-mode-stop
          - condition: trigger
            id: power-off
          - condition: trigger
            id: power-restored
    then:
      - service: script.light_handler
        data:
          light:
            entity_id: light.hall_9w
          power_mode: 'Off'
          brightness: 1
