alias: 'Backup : 💾 PFSense Config'

id: e9d3f556-6665-4f61-9db4-6cc0cd3c4f01

mode: single

trigger:
  - platform: webhook
    webhook_id: !secret start_pfsense_backup

action:
  - service: logbook.log
    data:
      name: PFSense Backup
      message: Started

  - service: shell_command.upload_config_to_github

  - wait_for_trigger:
      - platform: webhook
        webhook_id: !secret success_pfsense_backup
    timeout: '00:01:00'
    continue_on_timeout: false

  - service: logbook.log
    data:
      name: PFSense Backup
      message: Finished