alias: 'HA 📂 Folder Watch : /config/integrations/automations'

mode: restart

id: 7518b7c5-1b7a-4fd4-957e-706634b4256d

trigger:
  - platform: event
    event_type: folder_watcher


condition:
  - condition: template
    value_template: "{{ 'automations' in  trigger.event.data.folder }}"

action:
  - delay:
      milliseconds: 100
  - service: notify.persistent_notification
    data:
      title: Automations
      message: 'Reloaded'
  - service: homeassistant.check_config
  - service: automation.reload