alias: 'HA 📂 Folder Watch : /config/entities/input_button'

mode: restart

id: c7c7cf45-cddb-463e-ab24-dc2ac56f332d

trigger:
  - platform: event
    event_type: folder_watcher

condition:
  - condition: template
    value_template: "{{ 'input_button' in  trigger.event.data.folder }}"

action:
  - delay:
      milliseconds: 25

  - service: input_button.reload

  - service: notify.persistent_notification
    data:
      title: Input Button
      message: 'Reloaded'
