alias: 'HA 📂 Folder Watch : /config/entities/input_boolean'

mode: restart

id: 9fcfdd4f-6fca-4aaa-8596-c157c194272c

trigger:
  - platform: event
    event_type: folder_watcher

condition:
  - condition: template
    value_template: "{{ 'input_boolean' in  trigger.event.data.folder }}"

action:
  - delay:
      milliseconds: 25

  - service: input_boolean.reload

  - service: notify.persistent_notification
    data:
      title: Input Boolean
      message: 'Reloaded'
