alias: 'HA 📂 Folder Watch : /config/entities/input_datetime'

mode: restart

id: 9f89b9ab-8d0a-48d6-bd6c-aa8efc63c0fc

trigger:
  - platform: event
    event_type: folder_watcher

condition:
  - condition: template
    value_template: "{{ 'input_datetime' in  trigger.event.data.folder }}"

action:
  - delay:
      milliseconds: 25

  - service: input_datetime.reload

  - service: notify.persistent_notification
    data:
      title: Input Date & Times
      message: 'Reloaded'
