alias: 'HA 📂 Folder Watch : /config/integrations/shell_scripts'

mode: restart

id: a4747171-4f01-4fc9-a02b-4df51b33db06

trigger:
  - platform: event
    event_type: folder_watcher
    event_data:
      event_type: created

  - platform: event
    event_type: folder_watcher
    event_data:
      event_type: moved

condition:
  - condition: template
    value_template: "{{ 'shell_scripts' in  trigger.event.data.folder }}"

action:
    - service: shell_command.update_shell_script_permission
    - service: notify.persistent_notification
      data:
        title: Shell Scripts
        message: "File Permission updated"