esphome:
  name: esp32
  friendly_name: esp32

esp32:
  board: node32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "oCDnJFw2z3De39UTOWZDufW5SXk8iwFiCraZ9MvUyVE="

ota:
  - platform: esphome
    password: "c50acb67ca44f4fcda1a70f97b2c981f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Fallback Hotspot"
    password: "OQIounoFbIat"

captive_portal:
    