esphome:
  name: pwm_fan_controller
  on_boot:
    - priority: 200.0
      then:
        - output.set_level:
            id: cabfan
            level: 100%

esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.7.205

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-79E330"
    password: "klbyZ8z8ZDca"

captive_portal:
    

switch:
  - platform: restart
    name: "Restart"

  - platform: shutdown
    name: "Shutdown"

  - platform: gpio
    name: "Relay"
    inverted: true
    pin: 
      number: GPIO27


sensor:
# Reports RPM by pulse_counter
  - platform: pulse_counter
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
    name: Fan Speed
    update_interval: 1s
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    
output:
  - platform: ledc
    pin: GPIO14
    frequency: 25000 Hz
    id: cabfan

fan:
  - platform: speed
    output: cabfan
    name: "Network Cabinet Fan"