alias: '🆙 Updater : 🤏 Pi-Hole - Remote'

id: 69c4403a-e1c4-4f76-ad87-9fad62457b56

mode: queued

trigger:
  - platform: state
    entity_id:
      - update.pi_hole_dns_over_tcp_udp_core_update_available
      - update.pi_hole_dns_over_tcp_udp_ftl_update_available
      - update.pi_hole_dns_over_tcp_udp_web_update_available
    to: 'on'
    from: 'off'


action:
  - service: shell_command.pihole_updater
    data:
      identity: remote

  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0

  - service: homeassistant.reload_config_entry
    target:
      device_id: 24ff7c89b0d9ef054db14aecf7bda019

  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0

  - if:
      - condition: template
        value_template: >-
          {{ is_state('update.pi_hole_dns_over_tcp_udp_core_update_available', 'off') and
          is_state('update.pi_hole_dns_over_tcp_udp_ftl_update_available', 'off') and
          is_state('update.pi_hole_dns_over_tcp_udp_web_update_available', 'off') }}
    then:
      - service: notify.persistent_notification
        data:
          title: ✅ Pi-Hole - Remote
          message: Updated & Restarted
    else:
      - service: notify.persistent_notification
        data:
          title: ‼️Pi-Hole - Remote
          message: Update Failed / Unknown Error Occured

