alias: '🆙 Updater : 🤏 Pi-Hole - Private DNS'

id: d3de73ce-4138-4346-8932-52c08e66a309

mode: queued

trigger:
  - platform: state
    entity_id:
      - update.pi_hole_core_update_available
      - update.pi_hole_ftl_update_available
      - update.pi_hole_web_update_available
    to: 'on'
    from: 'off'


action:
  - service: shell_command.pihole_updater
    data:
      identity: privatedns

  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0

  - service: homeassistant.reload_config_entry
    target:
      device_id: 1e60a7536164885d81d0427e5db9a041

  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0

  - if:
      - condition: template
        value_template: >-
          {{ is_state('update.pi_hole_core_update_available', 'off') and
          is_state('update.pi_hole_ftl_update_available', 'off') and
          is_state('update.pi_hole_web_update_available', 'off') }}
    then:
      - service: notify.persistent_notification
        data:
          title: ✅ Pi-Hole - Private DNS
          message: Updated & Restarted
    else:
      - service: notify.persistent_notification
        data:
          title: ‼️Pi-Hole - Private DNS
          message: Update Failed / Unknown Error Occured

