---
# Sets up Home Assistant.
#
# Basically, everything that doesn't have to be in the
# main configuration.yaml.
#
# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
    # Lets me customize individual entities
    customize: !include_dir_merge_named ../entities/customizations