esphome:
  name: esp32dev
  friendly_name: esp32dev

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "n/lS6a7rPr6+ZTQtp4gdn0aKu+xlljSQBLfd+CH6w5s="

ota:
  - platform: esphome
    password: "00fb8b50b3dd72fcd059dcf6e4642087"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Dev Fallback Hotspot"
    password: "tJslYqWSgNX4"

captive_portal:
    