esphome:
  name: kkotha

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "f8dbf08dca7f373f20d59fa08b2a793f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kkotha Fallback Hotspot"
    password: "IxsxRoLyoLNc"

captive_portal:


text_sensor:
  - platform: version
    name: "Firmware Version"
    id: kkotha_version
    hide_timestamp: true

  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    mac_address:
      name: Mac Address

switch:
  - platform: restart
    name: "Restart"

  - platform: shutdown
    name: "Shutdown"
    
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: kkotha_wifi_signal
    update_interval: 60s