alias: "HA : 📝 Log Levels"
id: d2c0ed98-6bb6-4d88-bbbb-3b382bdcb82b
mode: restart
description: Dynamically set the log levels without having to restart HASS or edit configuration.yaml

trigger:
    - platform: state
      entity_id: input_select.log_level

action:
    - service: logger.set_level
      data:
          homeassistant.components: "{{ states.input_select.log_level.state }}"
