esphome:
  name: airfreshener-d1mini
  friendly_name: AirFreshener-D1Mini

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.7.208
  ap:
    ssid: "Airfreshener-D1Mini"
    password: "0WmkwIenwEhg"

captive_portal:

switch:
  - platform: gpio
    pin: 
      number: GPIO05
      mode:
        output: true

    id: relay
    name: "Spary Now"
    icon: "mdi:scent"