esphome:
  name: backcorridor
  friendly_name: "Back Corridor"
  
esp8266:
  board: nodemcuv2

logger:

# Safe Mode
safe_mode:
  disabled: false
  reboot_timeout: 5min
  num_attempts: 5


# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_key

wifi:
  ssid: !secret wifi_ssid_internal
  password: !secret wifi_password
  use_address: 10.0.7.23

  ap:
    ssid: "Back-Corridor Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

binary_sensor:

  - platform: status
    name: Status
    icon: mdi:network-pos
    disabled_by_default: false

  - platform: gpio
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
    name: "Hall Rear Door"
    device_class: door
    
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
    name: "Kitchen Door"
    device_class: door

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: personal_bedroom_clock_wifi_signal
  
  - platform: adc
    pin: VCC
    name: "Chip Voltage"
    entity_category: diagnostic
    disabled_by_default: False

text_sensor:
  - platform: version
    name: "Firmware Version"
    id: back_corridor_version
    hide_timestamp: true

  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Address

switch:
  - platform: restart
    name: "Back Corridor Restart"

  - platform: shutdown
    name: "Back Corridor Shutdown"