esphome:
  name: back-corridor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "OyMaOZBUb9wDe6McrXgt+GZYI0kmPDjzPwTK5QrTwss="

ota:
  password: "88082546ab28e2de6bdb9042a12d79b1"

wifi:
  ssid: !secret wifi_ssid_internal
  password: !secret wifi_password
  use_address: 10.0.7.211

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Back-Corridor Fallback Hotspot"
    password: "Jtmfodi4lqQE"

captive_portal:
    
binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: "Hall Rear Door"
    device_class: door
    
text_sensor:
  - platform: version
    name: "Firmware Version"
    id: back_corridor_version
    hide_timestamp: true

  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Address

switch:
  - platform: restart
    name: "Back Corridor : Restart"

  - platform: shutdown
    name: "Back Corridor : Shutdown"