esphome:
  name: back-corridor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_key

wifi:
  ssid: !secret wifi_ssid_internal
  password: !secret wifi_password
  use_address: 10.0.7.22


  ap:
    ssid: "Back-Corridor Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:
    
binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode:
        input: true
        pullup: true
    name: "Hall Rear Door"
    device_class: door
    
  - platform: gpio
    pin:
      number: D3
      mode:
        input: true
        pullup: true
    name: "Kitchen Door"
    device_class: door
    
text_sensor:
  - platform: version
    name: "Firmware Version"
    id: back_corridor_version
    hide_timestamp: true

  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Address

switch:
  - platform: restart
    name: "Back Corridor Restart"

  - platform: shutdown
    name: "Back Corridor Shutdown"