esphome:
  name: display-test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "7612b7035731db5b1489ad6cf42408d9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.7.205

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Display-Test Fallback Hotspot"
    password: "Ye0VOsSrNV4g"

captive_portal:
    
i2c:
  sda: GPIO4
  scl: GPIO2
  
font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto_welcome
    size: 20

  - file: "gfonts://Roboto"
    id: roboto_msg
    size: 10

interval:
  - interval: 5s
    then:
      - display.page.show_next: my_display
      - component.update: my_display

image:
  - file: "kkotha.jpg"
    id: my_image
    resize: 64x128
    
animation:
  - file: "cute-kitty.gif"
    id: my_animation
    resize: 64x128

qr_code:
  - id: homepage_qr
    value: nordlich.com
    
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: my_display
    #reset_pin: D0
    pages:
      - id: page1
        lambda: |-
          it.print(0, 0, id(roboto_welcome), "Hi Karthik");
          it.print(0, 30, id(roboto_msg), "Hope You Are Doing Good.");
      - id: page2
        lambda: |-
          it.image(0, 0, id(my_image));
      - id: page3
        lambda: |-
          id(my_animation).next_frame();
          it.image(0, 0, id(my_animation), COLOR_ON, COLOR_OFF);
      - id: page4
        lambda: |-
          it.qr_code(50, 0, id(homepage_qr), Color(255,255,255), 2);
          
      