esphome:
  name: dummy-esp8266
  friendly_name: dummy-esp8266

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "T+QwDXqnbpvsujUhM++3+t8QgivZu7r/1tTO3qkPXSg="

ota:
  - platform: esphome
    password: "7bbd174f52eeba089f59f017664ee30d"

wifi:
  ssid: !secret wifi_ssid_internal
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dummy-Esp8266 Fallback Hotspot"
    password: "6QHZODUtzJkE"

captive_portal:
    