esphome:
  name: first-floor-hall-door-buzzer
  friendly_name: First Floor Hall Door Buzzer (D1MINI)

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.7.208

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "First-Floor-Hall-Door-Buzzer"
    password: !secret wifi_fallback_password

captive_portal:


switch:
  - platform: gpio
    on_turn_on:
    - delay: 15s
    - switch.turn_off: relay
    pin: 
      number: GPIO14
      mode: 
        output: True
        open_drain: True
    id: relay
    name: "On / Off"
    icon: "mdi:scent"