esphome:
  name: weather-station

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: !secret ota_key_old

wifi:
  ssid: !secret wifi_ssid_internal
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather-Station Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80

text_sensor:
  - platform: version
    name: "Firmware Version"
    id: weather_station_version
    hide_timestamp: true

  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Address

switch:
  - platform: restart
    name: "Restart"

  - platform: shutdown
    name: "Shutdown"
  
  
#i2c:
  #sda: D6
  #scl: D7
  #scan: true
  #id: i2c_bus_bmp280
  
  
sensor:

  #- platform: bmp280_i2c
    #i2c_id: i2c_bus_bmp280
    #temperature:
    #  name: "bmp280 Temperature"
    #  oversampling: 16x
    #pressure:
    #  name: "Air Pressure"
    #address: 0x76
    #update_interval: 120s
    
  - platform: dht
    pin: D5
    update_interval: 120s
    model: AM2302
    temperature:
      name: "Temperature"
      id: weather_station_temperature
    humidity:
      name: "Humidity"
      id: weather_station_humidity

  - platform: wifi_signal
    name: "WiFi Signal"
    id: weather_station_wifi_signal
    update_interval: 60s