alias: "💻 - Personal Laptop"

id: 64708b85-77f6-46c4-b778-1fb6b9aa7ec4

mode: restart

trigger:
  - platform: state
    entity_id:
      - sensor.sribhuvan_laptop_session_state
    from: Locked
    to: Unlocked
    id: unlocked

  - platform: state
    entity_id:
      - sensor.sribhuvan_laptop_session_state
    from: Unlocked
    to: Locked
    id: locked

  - platform: state
    entity_id:
      - sensor.sribhuvan_laptop_session_state
    from: Locked
    to: unavailable
    id: pc-off

  - platform: state
    entity_id:
      - sensor.sribhuvan_laptop_session_state
    from: Unlocked
    to: unavailable
    id: pc-off


action:
  - if:
      - condition: trigger
        id: locked
    then:
      - if:
          - condition: state
            entity_id: >-
              input_boolean.office_remember_light_state_when_locked_restore_when_unlocked
            state: "on"
        then:
          - service: script.office_lights
            data:
              action: Save State
              target:
                entity_id:
                  - light.office_light_1
                  - light.office_light_2
      - if:
          - condition: state
            entity_id: input_boolean.office_auto_turn_off_lights_when_pc_locked
            state: "on"
        then:
          - service: script.office_lights
            data:
              action: On PC Lock / Shutdown
  - if:
      - condition: trigger
        id: unlocked
    then:
      - if:
          - condition: state
            entity_id: input_boolean.office_auto_turn_on_lights_when_pc_unlocked
            state: "on"
          - condition: state
            entity_id: >-
              input_boolean.office_remember_light_state_when_locked_restore_when_unlocked
            state: "on"
        then:
          - service: script.office_lights
            data:
              action: Restore State
      - if:
          - condition: state
            entity_id: input_boolean.office_auto_turn_on_lights_when_pc_unlocked
            state: "on"
          - condition: state
            entity_id: >-
              input_boolean.office_remember_light_state_when_locked_restore_when_unlocked
            state: "off"
        then:
          - service: script.office_lights
            data:
              action: Power On
              target:
                entity_id: light.office_light_1
          - service: script.office_lights
            data:
              action: Power Off
              target:
                entity_id: light.office_light_2
  - if:
      - condition: trigger
        id: pc-off
    then:
      - if:
          - condition: state
            entity_id: input_boolean.office_auto_turn_off_lights_when_pc_shutdown
            state: "on"
        then:
          - service: script.office_lights
            data:
              action: On PC Lock / Shutdown