alias: '📦 Vault-1 : Storage Server '

id: "70c1c9ef-bf31-48be-980b-d708081f446d"

description: ''

mode: single

trigger:

  - platform: state
    entity_id:
      - input_boolean.power_vault1
    from: 'off'
    to: 'on'
    id: power-up

  - platform: state
    entity_id:
      - input_boolean.power_vault1
    from: 'on'
    to: 'off'
    id: power-down


  - platform: webhook
    webhook_id: !secret start_vault1
    id: power-on

  - platform: webhook
    webhook_id: !secret stop_vault1
    id: power-off


action:
  - choose:
      - conditions:
          - condition: trigger
            id: power-up
        sequence:
          - if:
              - condition: state
                entity_id: switch.sp_vault_1_nas
                state: 'off'
            then:
              - service: switch.turn_on
                target:
                  entity_id: switch.sp_vault_1_nas

            else:
              - if:
                  -  condition: state
                     entity_id: switch.sp_vault_1_nas
                     state: 'on'
                then:
                  - service: notify.persistent_notification
                    data:
                      title: Vault-1 Power Up
                      message: Server Is Already Running

                  - service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.power_vault1
                else:
                  - service: notify.persistent_notification
                    data:
                      title: Vault-1 Power Up
                      message: Server Smart Switch Is Unavailable

                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.power_vault1

      - conditions:
          - condition: trigger
            id: power-down
        sequence:
          - if:
              - condition: state
                entity_id: switch.sp_vault_1_nas
                state: 'on'
                for:
                  hours: 0
                  minutes: 3
                  seconds: 0
            then:
              - service: shell_command.vault1_power_off

              - delay:
                  minutes: 10

              - service: switch.turn_off
                target:
                  entity_id: switch.sp_vault_1_nas
            else:
              - if:
                  - condition: state
                    entity_id: switch.sp_vault_1_nas
                    state: 'on'
                then:
                  - service: notify.persistent_notification
                    data:
                      title: Vault-1 Power Down
                      message: Server Is Still Booting

                  - service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.power_vault1
                else:
                  - if:
                      - condition: state
                        entity_id: switch.sp_vault_1_nas
                        state: 'off'
                    then:
                      - service: notify.persistent_notification
                        data:
                          title: Vault-1 Power Down
                          message: Server Already Powered Down
                    else:
                      - service: notify.persistent_notification
                        data:
                          title: Vault-1 Power Down
                          message: Server Smart Switch Is Unavailable

                      - service: input_boolean.turn_on
                        target:
                          entity_id: input_boolean.power_vault1

      - conditions:
          - condition: trigger
            id: power-on
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.sp_vault_1_nas

          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.power_vault1

      - conditions:
          - condition: trigger
            id: power-off
        sequence:
          - delay:
              hours: 0
              minutes: 2
              seconds: 0
              milliseconds: 0

          - service: switch.turn_off
            target:
              entity_id: switch.sp_vault_1_nas

          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.power_vault1

    default: []